### ISSUE TITLE
Fail to build environment_cp both Day 4 and Day 5

### ISSUE THREAD

**Issue by pwalczysko** [ome/EMBL-EBI-imaging-course-04-2024#2]
On the Linux VM Day 4 cellprofiler env build fails with

```
    /tmp/pip-build-env-2pbks69z/normal/lib/python3.8/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-pmbnfk13/centrosome_2b604ded1ce8454f91ccb472bbdfc7a2/centrosome/_propagate.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
            heap.ptrs[child][k] = new_elem[k]
        heap.items += 1
      
        # restore heap invariant, all parents <= children
        while child>0:
            parent = (child + 1) / 2 - 1 # __parent(i)
                                     ^
      ------------------------------------------------------------
      
      centrosome/heap.pxd:148:31: Cannot assign type 'double' to 'unsigned int'
      Compiling centrosome/_propagate.pyx because it changed.
      Compiling centrosome/_cpmorphology2.pyx because it changed.
      Compiling centrosome/_convex_hull.pyx because it changed.
      Compiling centrosome/_fastemd.pyx because it changed.
      Compiling centrosome/_filter.pyx because it changed.
      Compiling centrosome/_lapjv.pyx because it changed.
      [1/6] Cythonizing centrosome/_convex_hull.pyx
      [2/6] Cythonizing centrosome/_cpmorphology2.pyx
      [3/6] Cythonizing centrosome/_fastemd.pyx
      [4/6] Cythonizing centrosome/_filter.pyx
      [5/6] Cythonizing centrosome/_lapjv.pyx
      [6/6] Cythonizing centrosome/_propagate.pyx
      Traceback (most recent call last):
        File "/home/training/miniconda3/envs/imaging_course_cp_day4_2024/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/training/miniconda3/envs/imaging_course_cp_day4_2024/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/training/miniconda3/envs/imaging_course_cp_day4_2024/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-2pbks69z/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-2pbks69z/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-2pbks69z/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 89, in <module>
        File "/tmp/pip-build-env-2pbks69z/normal/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-2pbks69z/normal/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: centrosome/_propagate.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

failed

CondaEnvException: Pip failed
```

On the Linux VM Day 5 Cellprofiler build fails with

```
stall-bxlzz3lv/centrosome_0d701048d79245f88a0b4e72628ad0a5/centrosome/_cpmorphology2.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      /tmp/pip-build-env-b66uhii6/normal/lib/python3.8/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-bxlzz3lv/centrosome_0d701048d79245f88a0b4e72628ad0a5/centrosome/_fastemd.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      /tmp/pip-build-env-b66uhii6/normal/lib/python3.8/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-bxlzz3lv/centrosome_0d701048d79245f88a0b4e72628ad0a5/centrosome/_filter.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      /tmp/pip-build-env-b66uhii6/normal/lib/python3.8/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-bxlzz3lv/centrosome_0d701048d79245f88a0b4e72628ad0a5/centrosome/_lapjv.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      warning: centrosome/_lapjv.pyx:281:12: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
      warning: centrosome/_lapjv.pyx:281:18: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
      /tmp/pip-build-env-b66uhii6/normal/lib/python3.8/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-bxlzz3lv/centrosome_0d701048d79245f88a0b4e72628ad0a5/centrosome/_propagate.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
            heap.ptrs[child][k] = new_elem[k]
        heap.items += 1
      
        # restore heap invariant, all parents <= children
        while child>0:
            parent = (child + 1) / 2 - 1 # __parent(i)
                                     ^
      ------------------------------------------------------------
      
      centrosome/heap.pxd:148:31: Cannot assign type 'double' to 'unsigned int'
      Compiling centrosome/_propagate.pyx because it changed.
      Compiling centrosome/_cpmorphology2.pyx because it changed.
      Compiling centrosome/_convex_hull.pyx because it changed.
      Compiling centrosome/_fastemd.pyx because it changed.
      Compiling centrosome/_filter.pyx because it changed.
      Compiling centrosome/_lapjv.pyx because it changed.
      [1/6] Cythonizing centrosome/_convex_hull.pyx
      [2/6] Cythonizing centrosome/_cpmorphology2.pyx
      [3/6] Cythonizing centrosome/_fastemd.pyx
      [4/6] Cythonizing centrosome/_filter.pyx
      [5/6] Cythonizing centrosome/_lapjv.pyx
      [6/6] Cythonizing centrosome/_propagate.pyx
      Traceback (most recent call last):
        File "/home/training/miniconda3/envs/imaging_course_cp_day5_2024/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/training/miniconda3/envs/imaging_course_cp_day5_2024/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/training/miniconda3/envs/imaging_course_cp_day5_2024/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-b66uhii6/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-b66uhii6/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-b66uhii6/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 89, in <module>
        File "/tmp/pip-build-env-b66uhii6/normal/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-b66uhii6/normal/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: centrosome/_propagate.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

failed

CondaEnvException: Pip failed
```

**Comment by jburel** [comment]
https://github.com/ome/EMBL-EBI-imaging-course-04-2024/pull/14
