### ISSUE TITLE
Conversion and minio day 5 - napari on Linux VM

### ISSUE THREAD

**Issue by pwalczysko** [ome/EMBL-EBI-imaging-course-04-2024#5]
Fails with

```
ng-course-04-2024$ napari /tmp/conversion_out/B4_C3.ome.zarr/0
WARNING: Could not load the Qt platform plugin "xcb" in "" even though it was found.
18:03:28 WARNING Could not load the Qt platform plugin "xcb" in "" even though it was found.
WARNING: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

18:03:28 WARNING This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
```

Note: This works fine locally on my Mac M1

**Comment by pwalczysko** [comment]
This is fixed, napari opens.

A follow-up problem, only in the minio workflow, and only on the LInux VM (Mac M1 is fine):

```
napari 6001240.zarr
....
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/training/miniconda3/envs/imaging_course_minio_day5_2024/lib/python3.9/site-packages/napari/_qt/qt_viewer.py", line 966, in _qt_open
    self.viewer.open(
  File "/home/training/miniconda3/envs/imaging_course_minio_day5_2024/lib/python3.9/site-packages/napari/components/viewer_model.py", line 1105, in open
    layers = self._open_or_raise_error(
  File "/home/training/miniconda3/envs/imaging_course_minio_day5_2024/lib/python3.9/site-packages/napari/components/viewer_model.py", line 1214, in _open_or_raise_error
    raise ReaderPluginError(
napari.errors.reader_errors.ReaderPluginError: Tried opening with napari-ome-zarr, but failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/training/miniconda3/envs/imaging_course_minio_day5_2024/bin/napari", line 8, in <module>
    sys.exit(main())
  File "/home/training/miniconda3/envs/imaging_course_minio_day5_2024/lib/python3.9/site-packages/napari/__main__.py", line 570, in main
    _run()
  File "/home/training/miniconda3/envs/imaging_course_minio_day5_2024/lib/python3.9/site-packages/napari/__main__.py", line 340, in _run
    viewer._window._qt_viewer._qt_open(
  File "/home/training/miniconda3/envs/imaging_course_minio_day5_2024/lib/python3.9/site-packages/napari/_qt/qt_viewer.py", line 974, in _qt_open
    handle_gui_reading(
  File "/home/training/miniconda3/envs/imaging_course_minio_day5_2024/lib/python3.9/site-packages/napari/_qt/dialogs/qt_reader_dialog.py", line 201, in handle_gui_reading
    open_with_dialog_choices(
  File "/home/training/miniconda3/envs/imaging_course_minio_day5_2024/lib/python3.9/site-packages/napari/_qt/dialogs/qt_reader_dialog.py", line 294, in open_with_dialog_choices
    qt_viewer.viewer.open(paths, stack=stack, plugin=plugin_name, **kwargs)
  File "/home/training/miniconda3/envs/imaging_course_minio_day5_2024/lib/python3.9/site-packages/napari/components/viewer_model.py", line 1095, in open
    self._add_layers_with_plugins(
  File "/home/training/miniconda3/envs/imaging_course_minio_day5_2024/lib/python3.9/site-packages/napari/components/viewer_model.py", line 1295, in _add_layers_with_plugins
    layer_data, hookimpl = read_data_with_plugins(
  File "/home/training/miniconda3/envs/imaging_course_minio_day5_2024/lib/python3.9/site-packages/napari/plugins/io.py", line 77, in read_data_with_plugins
    res = _npe2.read(paths, plugin, stack=stack)
  File "/home/training/miniconda3/envs/imaging_course_minio_day5_2024/lib/python3.9/site-packages/napari/plugins/_npe2.py", line 63, in read
    layer_data, reader = io_utils.read_get_reader(
  File "/home/training/miniconda3/envs/imaging_course_minio_day5_2024/lib/python3.9/site-packages/npe2/io_utils.py", line 66, in read_get_reader
    return _read(
  File "/home/training/miniconda3/envs/imaging_course_minio_day5_2024/lib/python3.9/site-packages/npe2/io_utils.py", line 172, in _read
    if layer_data := read_func(paths, stack=stack):
  File "/home/training/miniconda3/envs/imaging_course_minio_day5_2024/lib/python3.9/site-packages/npe2/manifest/contributions/_readers.py", line 59, in npe1_compat
    return callable_(path)
  File "/home/training/miniconda3/envs/imaging_course_minio_day5_2024/lib/python3.9/site-packages/napari_builtins/io/_read.py", line 491, in _magic_imreader
    return [(magic_imread(path),)]
  File "/home/training/miniconda3/envs/imaging_course_minio_day5_2024/lib/python3.9/site-packages/napari_builtins/io/_read.py", line 219, in magic_imread
    image, zarr_shape = read_zarr_dataset(filename)
  File "/home/training/miniconda3/envs/imaging_course_minio_day5_2024/lib/python3.9/site-packages/napari_builtins/io/_read.py", line 129, in read_zarr_dataset
    image = [
  File "/home/training/miniconda3/envs/imaging_course_minio_day5_2024/lib/python3.9/site-packages/napari_builtins/io/_read.py", line 130, in <listcomp>
    read_zarr_dataset(os.path.join(path, subpath))[0]
  File "/home/training/miniconda3/envs/imaging_course_minio_day5_2024/lib/python3.9/site-packages/napari_builtins/io/_read.py", line 135, in read_zarr_dataset
    shape = image[0].shape
AttributeError: 'list' object has no attribute 'shape'
```

versions of napari-ome-zarr and napari (the same on M1 and Linux VM)

```
(imaging_course_minio_day5_2024) pwalczysko@Petrs-MBP EMBL-EBI-imaging-course-04-2024 % pip freeze | grep napari
napari==0.4.19.post1
napari-console==0.0.9
napari-ome-zarr==0.5.2
napari-plugin-engine==0.2.0
napari-plugin-manager==0.1.0a2
napari-svg==0.1.10
```

**Comment by pwalczysko** [comment]
This was solved now by the admin of the Linux VM. Closing.
